---
name: "Build Image and upload to ghcr"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iglu-cache:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-platforms = aarch64-linux
          extra-sandbox-paths = /usr/bin
    - name: Build container image
      id: build_image
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        for system in x86_64-linux aarch64-linux; do
          echo
          echo
          echo "Building docker for $system!"
          nix build .#packages.$system.iglu-cache-docker
          sudo docker load < result
          version=$(docker images | grep iglu-cache | head -n1 | awk '{print $2}' | cut -d- -f1)
        done

        echo
        echo
        echo "Pushing docker to ghcr.io!"
        docker tag iglu-cache:$version-arm64 ghcr.io/iglu-sh/iglu-cache:$version-arm64 
        docker tag iglu-cache:$version-amd64 ghcr.io/iglu-sh/iglu-cache:$version-amd64 
        docker push ghcr.io/iglu-sh/iglu-cache:$version-arm64 
        docker push ghcr.io/iglu-sh/iglu-cache:$version-amd64 

        for tag in latest $version; do
          echo
          echo
          echo "Creating multiarch image for $tag!"
          docker manifest create ghcr.io/iglu-sh/iglu-cache:$tag \
          --amend ghcr.io/iglu-sh/iglu-cache:$version-amd64 \
          --amend ghcr.io/iglu-sh/iglu-cache:$version-arm64
          docker manifest push ghcr.io/iglu-sh/iglu-cache:$tag
        done

  build-postgres:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/iglu-sh/postgres:latest

