---
name: "Check build"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check_build:
    strategy:
      matrix:
        system:
          - "x86_64-linux"
          - "aarch64-linux"
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
            extra-sandbox-paths = /usr/bin
      - name: "Build docker"
        run: nix build .#packages.${{ matrix.system }}.iglu-cache-docker

  build-postgres:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ghcr.io/iglu-sh/postgres:latest

